### PR TITLE
Add sketch for pad/lights support, ammend install instructions

### PR DESCRIPTION
**Pull request by 48productions**

### CODE REVIEW

**Comment by sugoku** [comment]
How did you wire up the MOSFETs? Do they get hot enough that you need a heatsink for them? I’m curious about the logic for the 5V to 12V conversion.

**Comment by 48productions** [comment]
I went ahead and threw together and committed a diagram of how I've wired up my cabinet, figured it'd be a good reference for how I did a lot of the wiring.

For each panel light, I hooked up an led strip to +12V, and the middle pin on a MOSFET. The MOSFET's rightmost pin I hooked up to ground, and the leftmost pin I connected to the output pin on the shift register for that panel. I also placed a 10k resistor across the left and right pins on the MOSFET as well.

As far as heatsinks went, the LEDs I threw in my panels draw less than the 2W max power the MOSFETs can handle without a heatsink, so I didn't end up using any on mine. If I used a different MOSFET that couldn't handle as much power or if I kept the original power-hungry CCFL lights in the panels, I might've ended up needing some. It all kinda depends on what your specific setup is like.

**Comment by ckdur** [comment]
Sorry for the delay. Working in a lot of stuff. The stuff is merging.
About the MOSFET stuff, I do not actually connect any kind of active circuitry to the Arduino boards. But your proposal is not a bad idea. The original controller uses Darlington drivers, probably because they are cheaper.
This project is actually aimed to just attach an Arduino to their original machines, in the case the PIUIO is unreachable, or just play original PIU games in the house.

**Comment by 48productions** [comment]
No worries about the delay. It's interesting to hear a bit more about what you've done/how the original hardware does things, IO-wise.

I'm also just using this project for my original machine, actually. In my case, my cab didn't come with a USB PIUIO (it just had the older MK4-era one), and I also wanted to replace my *very* questionable looking pad IO boards. Without the pad IOs (and thus the original pad light drivers), I ended up soldering together some boards with those MOSFET circuits to drive the pad lights instead, and hooked them up to an Arduino to get a replacement PIUIO.

I've honestly seen way better reliability with your Arduino-based PIUIO than I've seen on public cabs with real PIUIOs, so thanks for setting up the original project!

**Pull request merged**
